#!/bin/bash

## Files and cmd
CONF_DIR="$HOME/.config/hypr/themes/cyber/eww"
EWW="eww -c $CONF_DIR"

## Refresh Weather Cache
$CONF_DIR/scripts/weather --getdata &

## Run eww daemon if not running already
if [[ ! $(pidof eww) ]]; then
    ${EWW} daemon
    sleep 1
fi

## Open widgets
NB_MONITORS=($(hyprctl monitors -j | jq -r '.[] | .id'))
for i in "${!NB_MONITORS[@]}"; do
    ${EWW} open bar$i
    [[ $i == 0 ]] && ${EWW} open-many sidebar notifications
done
