#! /bin/bash

AWWW_TRANSITION=random
export stills="$1"

wallpaper() {
  for monitor in "${monitors[@]}"; do awww img --transition-type random --outputs $monitor "$(randstill)"; done
}

#Function to select a random file from $stills directory
randstill() {
  find "$stills" -maxdepth 1 -type f | shuf -n 1
}

#Switches wallpaper based on charging status
wptoggle() {
  #Identify active monitors
  monitors=($(hyprctl monitors | awk '{if ($1 ~ "Monitor") print $2}'))
  hyprctl keyword decoration:blur_new_optimizations 1

  wallpaper
  while pgrep awww; do
    sleep 300
    wallpaper
  done
}

#perform cleanup and exit
trap 'pkill awww & exit' exit 1 3 15

awww-daemon
wptoggle
